/******************************************
Treehouse FSJS Techdegree:
project 1 - A Random Quote Generator
******************************************/

/*** 
 * `quotes` array 
***/
var intervalID;

var quotes = [
  { quote: 'Be yourself; everyone else is already taken.',
    source:'Oscar Wilde', tags:'life' },

  { quote: 'There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.', 
    source:'Albert Einstein', tags:'life' },

  { quote: 'It is never too late to be what you might have been.', 
    source:'George Eliot', tags:'inspitational' },

  { quote: 'And once the storm is over, you won’t remember how you made it through, how you managed to survive. You won’t even be sure, whether the storm is really over. But one thing is certain. When you come out of the storm, you won’t be the same person who walked in. That’s what this storm’s all about.', 
    source:'Haruki Murakami', tags:'inspirational' },

  { quote: 'To the well-organized mind, death is but the next great adventure.', 
    source: 'J.K. Rowlings', citation: 'Harry Potter and the Sorcerer\'s Stone', year: '1997', tags:'thinking' },

  { quote: 'The world is indeed full of peril, and in it there are many dark places; but still there is much that is fair, and though in all lands love is now mingled with grief, it grows perhaps the greater.', 
    source:'J.R.R. Tolkien',citation:'The Fellowship of the Ring', year: '1954', tags:'hope' },

  { quote: 'And, when you want something, all the universe conspires in helping you to achieve it.', 
    source:'Paulo Coelho', citation: 'The Alchemist', year: '1988' ,tags:'optimism' },

  { quote: 'Pain is inevitable. Suffering is optional.', 
    source:'Haruki Murakami', citation: 'What I Talk About When I Talk About Running',year: '2007', tags:'inspirational' },
]

//generates a random number not higher than arr of obj length and  randomly picks one from the array including item in index 0
function getRandomQuote () {
  return quotes[Math.floor(Math.random() * quotes.length)];
}

//uses the object (quote) generated by getRandomQuote() and prints its elements using css properties
function printQuote () {
  var randQuote = getRandomQuote();
  var printHTML = '<p class="quote">' + randQuote.quote + '</p>';
  printHTML += '<p class="source">' + randQuote.source ;
  // checks if citation, year and tags exist withing the object and applies css styles to add is to the final print 
  if (randQuote.hasOwnProperty('citation')) {
      printHTML += '<span class="citation">' + randQuote.citation + '</span>' ;
  } 
  if (randQuote.hasOwnProperty('year')) {
      printHTML += '<span class="year">' + randQuote.year + '</span>';
  }
  if (randQuote.hasOwnProperty('tags')) {
      printHTML += '<span class="tags">' + randQuote.tags + '</span>';
  }    
  printHTML += '</p>';
  //links the final string to the HTML file
  document.getElementById('quote-box').innerHTML = printHTML;
  return printHTML;
}

//generates a random RGB color
function rgbBgColorRand (){
  var red = Math.floor(Math.random() * 255) + 1;
  var green = Math.floor(Math.random() * 255) + 1;
  var blue = Math.floor(Math.random() * 255) + 1;
  return 'rgb(' + red + ',' + green + ',' + blue + ')';
}

//function to change background-color property in CSS
function bgRand(){
  var backGround = document.querySelector("body");
  backGround.style.backgroundColor = rgbBgColorRand();
}

// function to auto refresh the quote and BGColor every set amount of seconds (has to be called at some point)
function quoteAutoRefresh (interval) {
  intervalQuote = setInterval(printQuote, interval);
  intervalColor = setInterval(bgRand, interval);
  }



document.getElementById('load-quote').addEventListener("click", printQuote, false);
//changes the back ground color everytime the button is clicked (using bgRand function)
document.getElementById('load-quote').addEventListener("click", bgRand, false);
//to avoid overlapping between the automatic and the manual(by clicking the button) as well as random BGcolor generation of the next quote
document.getElementById('load-quote').addEventListener("click", function() {
  clearInterval(intervalQuote);
  clearInterval(intervalColor);
  quoteAutoRefresh(3000);
});
quoteAutoRefresh(3000);
